steps:
  - name: python
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t',
           'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA', '.']

options:
  logging: CLOUD_LOGGING_ONLY